### ISSUE TITLE
Access rights

### ISSUE THREAD

**Issue by CapDev12** [Sovos-Compliance/mongo-delphi-driver-build#4]
Hi )
I want to compile mongoc_d32_v1-0-1.dll for  Convey-Compliance/mongo-delphi-driver

git.exe submodule update --init

Cloning into '__submodules/convey-private-libs'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Convey-Compliance/convey-private-libs.git' into submodule path '__submodules/convey-private-libs' failed

**Comment by jsbattig** [comment]
I will check. But that repo might not be needed for the purpose of using
the driver.
I think we included it just for certain tests.

**Comment by CapDev12** [comment]
How to selectively update _submodules ?

> git submodule update __submodules/mongo-delphi-driver

Cloning into '__submodules/mongo-delphi-driver'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Convey-Compliance/mongo-delphi-driver.git' into submodule path '__submodules/mongo-delphi-driver' failed

**Comment by jsbattig** [comment]
You need to have your ssh key registered with github.
mongo-delphi-driver repo is a public repo.
